### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by jeffersonquispe** [ayulockin/faceattributes#1]
Hi, in the next code line at Colab  show this error:
# Initilize a new wandb run
wandb.init(entity='ayush-thakur', project="multi-output-classifier")

 Logging results to Weights & Biases (Documentation).
Project page: https://app.wandb.ai/ayush-thakur/multi-output-classifier
Run page: https://app.wandb.ai/ayush-thakur/multi-output-classifier/runs/1ieeyq02

404 response executing GraphQL.
{"errors":[{"message":"project ayush-thakur/multi-output-classifier not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
wandb: ERROR Error while calling W&B API: project ayush-thakur/multi-output-classifier not found (<Response [404]>)
wandb: ERROR Permission denied to access ayush-thakur/multi-output-classifier/1ieeyq02
404 response executing GraphQL.
{"errors":[{"message":"project ayush-thakur/multi-output-classifier not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
wandb: ERROR Error while calling W&B API: project ayush-thakur/multi-output-classifier not found (<Response [404]>)
communication error with wandb Permission denied to access ayush-thakur/multi-output-classifier/1ieeyq02

**Comment by ayulockin** [comment]
This issue is because you are trying to use my entity name to log the metrics. 

You can sign up on [wandb.com](wandb.com) 

wandb.init(entity='your-username', project="new-project")
